version: '3'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sunho123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: sunho123
      AWS_REGION: ap-southeast-2
      AWS_S3_BUCKET: my-mapdata-bucket
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata:
